import { useMemo, useState } from 'react'
import { motion } from 'framer-motion'
import { CartesianGrid, Line, LineChart, ReferenceDot, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Beaker, ChevronDown, ClipboardList, FlaskConical, HelpCircle, Lightbulb } from 'lucide-react'
import type { ExperimentData } from '@shared/schemas'
import { compileFormula, fmt } from '@/lib/formula'
import { Param } from '@/sims/SimShell'
import { cn, isUrduScript } from '@/lib/utils'

const tip = { background: 'hsl(var(--card))', border: '1px solid hsl(var(--border))', borderRadius: 12, color: 'hsl(var(--foreground))' }

/** Interactive lab generated by the AI for THIS chapter: sliders → live results → graph → guided steps. */
export function CustomLab({ exp }: { exp: ExperimentData }) {
  const vars = exp.variables.filter((v) => Number.isFinite(v.min) && Number.isFinite(v.max) && v.max > v.min)
  const [values, setValues] = useState<Record<string, number>>(() =>
    Object.fromEntries(vars.map((v) => [v.id, Math.min(v.max, Math.max(v.min, v.value ?? (v.min + v.max) / 2))])),
  )
  const outputs = useMemo(
    () => exp.outputs.map((o) => ({ ...o, fn: compileFormula(o.formula, vars.map((v) => v.id)) })).filter((o) => o.fn),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [exp],
  )
  const [open, setOpen] = useState<number | null>(null)
  const rtl = isUrduScript(exp.title)

  const chartVar = vars.find((v) => v.id === exp.chart?.x) ?? vars[0]
  const chartOut = outputs.find((o) => o.id === exp.chart?.y) ?? outputs[0]
  const series = useMemo(() => {
    if (!chartVar || !chartOut?.fn) return []
    return Array.from({ length: 41 }, (_, i) => {
      const x = chartVar.min + ((chartVar.max - chartVar.min) * i) / 40
      const y = chartOut.fn!({ ...values, [chartVar.id]: x })
      return { x: Number(fmt(x)), y: Number.isFinite(y) ? Number(fmt(y)) : null }
    })
  }, [chartVar, chartOut, values])

  if (!exp.applicable || !vars.length || !outputs.length)
    return (
      <div className="surface p-6 md:p-8">
        <span className="chip-gold">
          <ClipboardList className="h-3 w-3" /> Hands-on activity
        </span>
        <h2 className={cn('mt-3 text-4xl', rtl && 'urdu')}>{exp.title}</h2>
        {exp.goal && <p className={cn('mt-2 text-muted-foreground', rtl && 'urdu')}>{exp.goal}</p>}
        {exp.background && <p className={cn('mt-4 leading-relaxed', rtl && 'urdu')}>{exp.background}</p>}
        <ol className="mt-6 space-y-3">
          {(exp.activity.length ? exp.activity : exp.steps).map((a, i) => (
            <li key={i} className="flex gap-3 rounded-2xl bg-secondary/60 p-4">
              <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-coral-soft text-sm font-bold text-coral">{i + 1}</span>
              <span className={cn(rtl && 'urdu')}>{a}</span>
            </li>
          ))}
        </ol>
        <Questions exp={exp} open={open} setOpen={setOpen} />
      </div>
    )

  return (
    <div className="space-y-4">
      <div className="surface p-6">
        <span className="chip-coral">
          <FlaskConical className="h-3 w-3" /> Made for this chapter
        </span>
        <h2 className={cn('mt-3 text-4xl', rtl && 'urdu')}>{exp.title}</h2>
        {exp.goal && <p className={cn('mt-1 text-muted-foreground', rtl && 'urdu')}>{exp.goal}</p>}
        {exp.background && <p className={cn('mt-3 text-sm leading-relaxed', rtl && 'urdu')}>{exp.background}</p>}
      </div>

      <div className="grid gap-4 lg:grid-cols-[1fr_320px]">
        <div className="surface p-5">
          {chartVar && chartOut && (
            <>
              <p className="mb-3 text-sm font-semibold">
                {chartOut.label} vs {chartVar.label}
              </p>
              <div className="h-72">
                <ResponsiveContainer width="100%" height="100%">
                  <LineChart data={series} margin={{ left: 8, right: 16, top: 8, bottom: 16 }}>
                    <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" />
                    <XAxis dataKey="x" type="number" domain={[chartVar.min, chartVar.max]} tick={{ fontSize: 11, fill: 'hsl(var(--muted-foreground))' }} label={{ value: `${chartVar.label}${chartVar.unit ? ` (${chartVar.unit})` : ''}`, position: 'insideBottom', offset: -8, fill: 'hsl(var(--muted-foreground))', fontSize: 12 }} />
                    <YAxis tick={{ fontSize: 11, fill: 'hsl(var(--muted-foreground))' }} width={48} />
                    <Tooltip
                      contentStyle={tip}
                      labelFormatter={(x) => `${chartVar.label}: ${x} ${chartVar.unit ?? ''}`}
                      formatter={(y) => [`${y} ${chartOut.unit ?? ''}`, chartOut.label]}
                    />
                    <Line name={chartOut.label} type="monotone" dataKey="y" stroke="hsl(var(--coral))" strokeWidth={3} dot={false} isAnimationActive={false} />
                    {Number.isFinite(chartOut.fn!(values)) && <ReferenceDot x={Number(fmt(values[chartVar.id]))} y={Number(fmt(chartOut.fn!(values)))} r={7} fill="hsl(var(--gold))" stroke="none" />}
                  </LineChart>
                </ResponsiveContainer>
              </div>
            </>
          )}
          <div className="mt-4 grid gap-3 sm:grid-cols-2 md:grid-cols-3">
            {outputs.map((o) => (
              <motion.div key={o.id} layout className="rounded-2xl bg-secondary/60 p-4">
                <p className="text-xs text-muted-foreground">{o.label}</p>
                <p className="text-2xl font-bold tabular-nums">
                  {fmt(o.fn!(values))} <span className="text-sm font-normal text-muted-foreground">{o.unit}</span>
                </p>
                <p className="mt-1 font-mono text-[11px] text-gold">{o.formula}</p>
                {o.explain && <p className="mt-1 text-xs text-muted-foreground">{o.explain}</p>}
              </motion.div>
            ))}
          </div>
        </div>
        <div className="surface h-fit space-y-5 p-5">
          <p className="section-label flex items-center gap-2">
            <Beaker className="h-3.5 w-3.5" /> Change the values
          </p>
          {vars.map((v) => (
            <Param
              key={v.id}
              label={v.label}
              value={values[v.id]}
              unit={v.unit ?? ''}
              min={v.min}
              max={v.max}
              step={v.step && v.step > 0 ? v.step : (v.max - v.min) / 100}
              onChange={(x) => setValues((s) => ({ ...s, [v.id]: x }))}
            />
          ))}
        </div>
      </div>

      {exp.steps.length > 0 && (
        <div className="surface p-5">
          <p className="section-label mb-3 flex items-center gap-2">
            <Lightbulb className="h-3.5 w-3.5" /> Try this
          </p>
          <ol className="space-y-2">
            {exp.steps.map((st, i) => (
              <li key={i} className="flex gap-3 text-sm">
                <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-coral-soft text-xs font-bold text-coral">{i + 1}</span>
                <span className={cn('pt-0.5', rtl && 'urdu')}>{st}</span>
              </li>
            ))}
          </ol>
        </div>
      )}
      <Questions exp={exp} open={open} setOpen={setOpen} />
    </div>
  )
}

function Questions({ exp, open, setOpen }: { exp: ExperimentData; open: number | null; setOpen: (i: number | null) => void }) {
  if (!exp.questions.length) return null
  return (
    <div className="surface mt-4 p-5">
      <p className="section-label mb-3 flex items-center gap-2">
        <HelpCircle className="h-3.5 w-3.5" /> Think about it
      </p>
      <div className="space-y-2">
        {exp.questions.map((q, i) => (
          <button key={i} onClick={() => setOpen(open === i ? null : i)} className="w-full rounded-2xl bg-secondary/60 p-4 text-left">
            <span className="flex items-center justify-between gap-3 font-semibold">
              {q.q}
              <ChevronDown className={cn('h-4 w-4 shrink-0 transition', open === i && 'rotate-180')} />
            </span>
            {open === i && <span className="mt-2 block text-sm text-muted-foreground">{q.a}</span>}
          </button>
        ))}
      </div>
    </div>
  )
}
