import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import type { Topic } from '@shared/schemas'

const COLORS = ['hsl(var(--coral))', 'hsl(var(--gold))', '#6FA8DC', 'hsl(var(--success))', '#B39DDB', '#F48FB1']
const tip = { background: 'hsl(var(--card))', border: '1px solid hsl(var(--border))', borderRadius: 12, color: 'hsl(var(--foreground))' }

/** Chart generated by the AI for numeric comparisons. */
export function AiChart({ chart }: { chart: NonNullable<Topic['chart']> }) {
  if (!chart.data?.length) return null
  const axis = { tick: { fontSize: 12, fill: 'hsl(var(--muted-foreground))' }, axisLine: false, tickLine: false }
  return (
    <div className="rounded-2xl border bg-background/50 p-4">
      {chart.title && <p className="mb-3 text-sm font-semibold">{chart.title}</p>}
      <div className="h-60">
        <ResponsiveContainer width="100%" height="100%">
          {chart.type === 'pie' ? (
            <PieChart>
              <Pie data={chart.data} dataKey="value" nameKey="label" innerRadius={50} outerRadius={90} paddingAngle={3} label={({ name }) => String(name)}>
                {chart.data.map((_, i) => (
                  <Cell key={i} fill={COLORS[i % COLORS.length]} stroke="none" />
                ))}
              </Pie>
              <Tooltip contentStyle={tip} />
            </PieChart>
          ) : chart.type === 'line' ? (
            <LineChart data={chart.data}>
              <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" />
              <XAxis dataKey="label" {...axis} />
              <YAxis {...axis} width={40} />
              <Tooltip contentStyle={tip} />
              <Line type="monotone" dataKey="value" stroke="hsl(var(--coral))" strokeWidth={3} dot={{ r: 5 }} />
            </LineChart>
          ) : (
            <BarChart data={chart.data}>
              <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" vertical={false} />
              <XAxis dataKey="label" {...axis} />
              <YAxis {...axis} width={40} />
              <Tooltip contentStyle={tip} cursor={{ fill: 'hsl(var(--secondary))' }} />
              <Bar dataKey="value" radius={[8, 8, 0, 0]}>
                {chart.data.map((_, i) => (
                  <Cell key={i} fill={COLORS[i % COLORS.length]} />
                ))}
              </Bar>
            </BarChart>
          )}
        </ResponsiveContainer>
      </div>
    </div>
  )
}
